# Site settings
title: Pham's website
email: me@quangpham.com
description: "My name is Quang Pham, a fullstack developer in Finland. This is my personal portfolio"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://localhost:4000/"
url: "http://quangpham.com/"
resume_url: about/quang_pham_resume.pdf
github_username:  quangpham
# Build settings
markdown: kramdown
paginate: 8
paginate_path: "/blog/page:num/"
nav_items:
- title: Home
  url: /
- title: About
  url: /about/
- title: Portfolio
  url: /portfolio/
- title: Blog
  url: /blog/
- title: Contact
  url: /contact/
